# Generated by Django 4.2 on 2023-04-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
